### ISSUE TITLE
PNG exporting is not working on macOS

### ISSUE THREAD

**Issue by hikalium** [nikosai/lambda-friends#28]
## How to reproduce this issue
1. Go http://nikosai.ml/lambda-friends/
1. Type `<2><2>` into text box and push send button.
1. Select グラフ tab and push start.
1. Push PNG button. This should start downloading an image of the graph. In fact, it just opens `about:blank` page and don't initiate a downloading process.

## Environment
```
Google Chrome | 69.0.3497.100 (Official Build) （64 ビット）
macOS High Sierra 10.13.6（17G65）
```

**Comment by nikosai** [comment]
I found an article that says `window.open(dataURL)` and all top-frame navigations to dataURL are now obsolete in Chrome (and deprecated even in Firefox).
https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/GbVcuwg_QjM%5B1-25%5D

Now we use `<a>` tag with download attribute instead of `window.open(dataURL)`. Thanks.
